export const ADD_ITEM = "ADD_ITEM";
export const LIFT_TOKEN_TO_STATE = "LIFT_TOKEN_TO_STATE";
export const LOGOUT = "LOGOUT";
export const REMOVE_TOKEN = "REMOVE_TOKEN";
export const CHECK_FOR_GOOGLE_USER = "CHECK_FOR_GOOGLE_USER";
export const SET_GOOGLE_USER = "SET_GOOGLE_USER";
export const REMOVE_GOOGLE_USER = "REMOVE_GOOGLE_USER";
export const SET_POINT = "SET_POINT";
